### ISSUE TITLE
Uninstalling SUIDGuard

### ISSUE THREAD

**Issue by carze** [sektioneins/SUIDGuard#5]
How would one go about uninstalling or reverting the changes made by the installer versions SUIDGuard? Wondering if it would cause issues in future OSX updates and also if some other official patch may be released.

**Comment by stefanesser** [comment]
To uninstall SUIDGuard one just needs to delete the directory /Library/Extension/SUIDGuard.kext and its content and ensure that /Library/Extension is touched once so that the kernel extension cache is rebuild.

We will most probably release an updated DMG that also contains an uninstaller soon.

Beside the fact that I do not recommend removing SUIDGuard any time soon.

**Comment by carze** [comment]
Thanks! Was just curious on ways to revert whenever an official patch comes out.
